### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by schungx** [alvinhochun/rhai-playground#12]
@alvinhochun  the new version will include:

* string interpolation `` `... ${...} ...` `` 
* line continuation `"......\`

To handle these, `TokenizeState` has a new field: `is_within_text_terminated_by` which is `Option<char>`.

|Type|Example|Return|`is_within_text_terminated_by`|
|-|-|-|-|
|Normal string|`"hello"`|`StringConstant`|`None`|
|Normal string unterminated|`"hello`|`LexError`|`None`|
|Normal string continued|`"hello\`|`StringConstant`|`Some('"')`|
|Literal string unterminated|`` `hello``|`StringConstant`|``Some('`')``|
|Literal string interpolated|`` `hello ${``|`InterpolatedString`|`None`|
|Literal string after interpolation|`` `... ${...} hello` ``|`StringConstant`|``Some('`')``|

When you see an `InterpolatedString`, you just push a level onto a stack, and start counting braces.  The next token will be the `{` of the `${`.  Once you finish the last closing `}` for the level, pop the stack, set ``state.is_within_text_terminated_by = Some("`")`` to continue parsing as string.

**Comment by alvinhochun** [comment]
Implemented in 02c3bc7 and deployed on https://rhai.rs/playground/dev/. Does it look right?

Not related to the tokenizer but I noticed that the parser panics (`panicked at 'internal error: entered unreachable code: expected a string within an interpolated string literal, but gets LexError(UnterminatedString)', D:\dev\toolchain\rust\cargo\git\checkouts\rhai-f99f240b2f7f4b04\10f334d\src\parser.rs:1050:35`) if an interpolated string is not terminated, like this:

```
`${}
```

**Comment by schungx** [comment]
Ah, good catch!  Let me check it out!

**Comment by schungx** [comment]
Fixed it.  Forgot to check the case of unterminated string.  I'll merge it to master in a bit.

> Implemented in [02c3bc7](https://github.com/rhaiscript/playground/commit/02c3bc7e6c1523afb62dd083c9255ffa9419ede8) and deployed on https://rhai.rs/playground/dev/. Does it look right?

It certainly looks _FINE_!

**Comment by schungx** [comment]
BTW, there is an updated `strings.rhai` version with multi-level interpolated strings.

**Comment by schungx** [comment]
The fix has landed inhttps://github.com/rhaiscript/rhai/pull/393

It no longer should panic...

**Comment by alvinhochun** [comment]
Done, updated!

**Comment by schungx** [comment]
![image](https://user-images.githubusercontent.com/661318/114274451-feedf180-9a50-11eb-98ed-0aacc8e86fb2.png)

Not sure why, but if a string is not terminated at the end of the line, now it colors all lines below as text.  `stable` doesn't do that.  Seems that the `is_within_text` property is not property cleared, but I should have cleared it together with raising the error.

So not sure where the problem is...

**Comment by schungx** [comment]
Ah, I think I found where the problem is.  It is in `get_next_token` when given an unterminated string.  I'll fix it.

**Comment by schungx** [comment]
OK, I should have fixed the bug with https://github.com/rhaiscript/rhai/pull/394

Please rebuild again to see if it solves the problem?

**Comment by alvinhochun** [comment]
Updated again.

**Comment by schungx** [comment]
Working fine!  However, just realized that I have a typo in `function_decl2.rhai`.

The line should be:

```rust
print(`addme(a, 4) should be 46: ${result}`);
```

I put the backtick in the wrong place...

**Comment by schungx** [comment]
@alvinhochun   I think it is time to move `dev` into `stable`?

**Comment by alvinhochun** [comment]
Done
