### ISSUE TITLE
About time to bump Rhai version?

### ISSUE THREAD

**Issue by schungx** [alvinhochun/rhai-playground#18]

**Comment by alvinhochun** [comment]
Right, I'll check tomorrow.

**Comment by alvinhochun** [comment]
Rhai 1.4.1 is published on https://rhai.rs/playground/dev/. If nothing special needs attention then we can run the workflow to copy it over to stable.

**Comment by schungx** [comment]
I think the `dev` version is stable, so it can be moved to `stable`!

**Comment by alvinhochun** [comment]
Done.

**Comment by schungx** [comment]
About time to bump... now at 1.7.0...

**Comment by alvinhochun** [comment]
Ah sorry, I updated the unstable build to 1.7.0 a few days ago but then forgot about it. I just deployed it to stable too.
