### ISSUE TITLE
Can't import modules

### ISSUE THREAD

**Issue by Estebang17-a** [alvinhochun/rhai-playground#20]
Hello!, can't import modules on the Rhai Playground, even the example code doesn't work. Could someone help out please? 

`import "BasicMathPackage" as mat;`

EXCEPTION: "Module not found: BasicMathPackage (line 3, position 8)"

**Comment by schungx** [comment]
The Playground doesn't support loading external modules.

@alvinhochun   maybe remove the module examples?

**Comment by alvinhochun** [comment]
I removed the example with 40a5302f38c54e922a458cfbfe81539ce2feb68e.
